/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.green.sahwang.model.payment.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentAvroStatus implements org.apache.avro.generic.GenericEnumSymbol<PaymentAvroStatus> {
  PAYING, PAID, COMPLETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentAvroStatus\",\"namespace\":\"com.green.sahwang.model.payment.avro\",\"symbols\":[\"PAYING\",\"PAID\",\"COMPLETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
