/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.green.sahwang.model.payment.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentAvroMethod implements org.apache.avro.generic.GenericEnumSymbol<PaymentAvroMethod> {
  CREDIT_CARD, ACCOUNT_TRANSFER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentAvroMethod\",\"namespace\":\"com.green.sahwang.model.payment.avro\",\"symbols\":[\"CREDIT_CARD\",\"ACCOUNT_TRANSFER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
