package com.green.sahwang.entity.enumtype;

public enum SaleStatus {
    CREATED, RECEIVING, RECEIVED, UNDER_REVIEW, LISTING, LISTED, ON_SALE, SOLD_OUT, SETTLEMENT_READY, SETTLEMENT_COMPLETE, READY, SHIPPED, COMPLETED
}
