version: '3.8'
services:
    # mysql 데이터베이스 서비스
  mysql:
    image: mysql:8.0.39
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234   # root 사용자 비밀번호 설정
      MYSQL_DATABASE: fourhwang                 # 기본 데이터베이스 설정
      MYSQL_USER: kty                     # 사용자 설정
      MYSQL_PASSWORD: kty1234        # 사용자 비밀번호 설정
    ports:
      - 3306:3306  # MariaDB의 포트를 호스트로 노출 (로컬 개발용)
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
    #   - mariadb_data:/var/lib/mysql  # 데이터가 유지되도록 볼륨을 사용

  # Spring Boot 애플리케이션 서비스 docker run -e
  springboot:
    image: taeyoungk/sahwang-app:latest  # 실제 빌드된 Spring Boot 애플리케이션 이미지
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/fourhwang?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root                       # 사용자
      SPRING_DATASOURCE_PASSWORD: 1234              #  사용자 비밀번호
      SERVER_PORT: 8080
      # SRPING_SQL_INIT_MODE: never
    ports:
      - 8080:8080  # Spring Boot 포트를 호스트로 노출
    depends_on:
      mysql:  # mysql 이 먼저 실행되도록 설정
        condition: service_healthy
    networks:
      - my_network

# 네트워크 설정
networks:
  my_network:
    driver: bridge